
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-01-29T09:08:11-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "616ec809a4fe373e1f63f50ed6756b254dcd63b9",
 "version": "0.6.post315+g616ec80"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
